name: Alphalens distribution

on: workflow_dispatch

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout alphalens
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Build wheels
        run: pipx run build

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist/*

      - name: Check metadata
        run: pipx run twine check dist/*

  upload_pypi:
    needs: [ dist ]
    runs-on: ubuntu-latest
    # upload to (Test)-PyPI on push with tag starting with v; diff by commit
    #    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: publish to testpypi
        uses: pypa/gh-action-pypi-publish@v1.4.1
        #        if: startsWith(github.event.head_commit.message, 'TEST')
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
#      - name: publish to pypi
#        uses: pypa/gh-action-pypi-publish@master
#        if: startsWith(github.event.head_commit.message, 'PYPI')
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_TOKEN }}
